namespace EPAPI.Repository.ReceiptEntry
{
    
    public class RcvParam
    {
        public string? poNum { get; set; }
        public string? PackSlip { get; set; }
        public string? receiptComment { get; set; }
        public int? VendorNum {  get; set; }
        public string? PurPoint { get; set; }
        public DateTime? ArrivalDate { get; set; }
        public string RowMod { get; set; }
        public int DrawSeq { get; set; } = 0;

        public string? nik {  get; set; }
        public string? password { get; set; }
    }
    public class RcvDtlParam
    {
        public string? PoNum { get; set; }
        public string? PoLine { get; set; }
        public string? PackSlip { get; set; }
        public int PackLine {  get; set; }
        public string? ReceiptComment { get; set; }
        public DateTime? ArrivalDate { get; set; }
        public string? ShipViaCode { get; set; }
        public string? QtyOption { get; set; }
        public double? InputOurQty { get; set; }
        public string? IUM { get; set; }
        public double? VendorQty { get; set; }
        public string? PUM { get; set; }
        public string? WarehouseCode { get; set; }
        public string? BinNum { get;  set; }
        public string? TranReference { get; set; }
        public bool ConvOverride { get; set; }
        public bool ReceivedComplete { get; set; }
        public bool Received { get; set; }
        public string ipReceived { get; set; }
        public string LegalNumber { get; set; }
        public bool IssuedComplete { get; set; }
        public int VendorNum { get; set; }
        public string LotNum { get; set; }
        public string PurPoint { get; set; }
        public string? RowMod { get; set; }

        public string nik { get; set; }
        public string password { get; set; }
    }
    public class RcvResponse {
        public Parameters parameters { get; set; }
    }
    public class RcvHead
    {
        public int? APTaxRoundOption { get; set; }
        public string? AddrList { get; set; }
        public string? AddrListFormatted { get; set; }
        public bool? AllowLCUpdate { get; set; }
        public bool? AllowUplift { get; set; }
        public decimal? AppliedLCAmt { get; set; }
        public decimal? AppliedLCVariance { get; set; }
        public decimal? AppliedRcptLCAmt { get; set; }
        public bool? ApplyToLC { get; set; }
        public DateTime? ArrivedDate { get; set; }
        public bool? AutoReceipt { get; set; }
        public int? AutoTranID { get; set; }
        public string? AutoTranType { get; set; }
        public int? BitFlag { get; set; }
        public bool? CNBonded { get; set; }
        public string? CNDeclarationBill { get; set; }
        public string? ChangeDate { get; set; }
        public string? ChangedBy { get; set; }
        public string? Company { get; set; }
        public int? ContainerID { get; set; }
        public string? CurrencyCode { get; set; }
        public decimal? DispLandedCost { get; set; }
        public string? DocNum_c { get; set; }
        public string? EntryDate { get; set; }
        public string? EntryPerson { get; set; }
        public string? GlbCompany { get; set; }
        public string? GlbPackSlip { get; set; }
        public string? GlbPurPoint { get; set; }
        public int? GlbVendorNum { get; set; }
        public decimal? GrossWeight { get; set; }
        public string? GrossWeightUOM { get; set; }
        public bool? HdrTaxNoUpdt { get; set; }
        public bool? ICLinked { get; set; }
        public string? ImportNum { get; set; }
        public int? ImportedFrom { get; set; }
        public string? ImportedFromDesc { get; set; }
        public decimal? InAppliedLCAmt { get; set; }
        public decimal? InAppliedLCVariance { get; set; }
        public decimal? InAppliedRcptLCAmt { get; set; }
        public decimal? InLCDutyAmt { get; set; }
        public decimal? InLCIndCost { get; set; }
        public decimal? InLCUpliftIndCost { get; set; }
        public decimal? InLCVariance { get; set; }
        public decimal? InLandedCost { get; set; }
        public bool? InPrice { get; set; }
        public decimal? InSpecDutyAmt { get; set; }
        public int? IntQueID { get; set; }
        public bool? Invoiced { get; set; }
        public string? LCComment { get; set; }
        public string? LCDisburseMethod { get; set; }
        public decimal? LCDutyAmt { get; set; }
        public decimal? LCIndCost { get; set; }
        public string? LCMessage { get; set; }
        public string? LCReference { get; set; }
        public decimal? LCUpliftIndCost { get; set; }
        public decimal? LCVariance { get; set; }
        public decimal? LandedCost { get; set; }
        public string? LegalNumber { get; set; }
        public string? LegalNumberMessage { get; set; }
        public decimal? OrigLandedCost { get; set; }
        public int? POLine { get; set; }
        public int? PONum { get; set; }
        public int? PORel { get; set; }
        public string? POType { get; set; }
        public string? POTypeDesc { get; set; }
        public string? PackSlip { get; set; }
        public bool? PartialReceipt { get; set; }
        public string? Plant { get; set; }
        public string? PurPoint { get; set; }
        public string? PurPointAddress1 { get; set; }
        public string? PurPointAddress2 { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointCountry { get; set; }
        public string? PurPointName { get; set; }
        public int? PurPointPrimPCon { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointZip { get; set; }
        public string? ReceiptComment { get; set; }
        public string? ReceiptDate { get; set; }
        public string? ReceivePerson { get; set; }
        public bool? Received { get; set; }
        public string? RowMod { get; set; }
        public bool? SaveForInvoicing { get; set; }
        public string? ShipViaCode { get; set; }
        public string? ShipViaCodeDescription { get; set; }
        public string? ShipViaCodeWebDesc { get; set; }
        public string? ShipViaDesc { get; set; }
        public decimal? SpecDutyAmt { get; set; }
        public int? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? TaxPoint { get; set; }
        public string? TaxRateDate { get; set; }
        public string? TaxRateGrpCode { get; set; }
        public string? TaxRegionCode { get; set; }
        public string? TaxRegionCodeDescription { get; set; }
        public bool? TaxesCalculated { get; set; }
        public decimal? TotDedTaxAmt { get; set; }
        public decimal? TotDutiesAmt { get; set; }
        public decimal? TotGrossWeight { get; set; }
        public string? TotGrossWeightUOM { get; set; }
        public decimal? TotIndirectCostsAmt { get; set; }
        public decimal? TotLinesAmt { get; set; }
        public decimal? TotSATaxAmt { get; set; }
        public decimal? TotTaxAmt { get; set; }
        public decimal? TotWHTaxAmt { get; set; }
        public decimal? TotWeight { get; set; }
        public string? TotWeightUOM { get; set; }
        public decimal? TotalAmt { get; set; }
        public string? TranDocTypeID { get; set; }
        public string? UD_SysRevID { get; set; }
        public bool? UpdateDtlArvdDate { get; set; }
        public bool? UpdateDtlRcptDate { get; set; }
        public bool? UpdateDtlRecs { get; set; }
        public decimal? UpliftPercent { get; set; }
        public int? VendorNum { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumState { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumZIP { get; set; }
        public decimal? Weight { get; set; }
        public string? WeightUOM { get; set; }
        public bool? XbSystAPTaxLnLevel { get; set; }
        public bool? XbSystReceiptTaxCalculate { get; set; }
        public string? aji_c { get; set; }
        public bool? eshReceived { get; set; }
        public bool? vrPONumCNBonded { get; set; }
        public string? vrPONumShipName { get; set; }
        public string? vrPONumShipToConName { get; set; }
    }
   
    public class RcvDtl
    {
        public bool? AllowLCUpdate { get; set; }
        public bool? AllowUpdSuppPrice { get; set; }
        public double? AppliedLCVariance { get; set; }
        public double? AppliedRcptLCAmt { get; set; }
        public DateTime? ArrivedDate { get; set; }
        public string? AsmPartDescription { get; set; }
        public int? AssemblySeq { get; set; }
        public string? AssemblySeqDescription { get; set; }
        public bool? AttributeBackoutRequired { get; set; }
        public bool? AttributeQtyMismatch { get; set; }
        public bool? AutoReceipt { get; set; }
        public string? BinNum { get; set; }
        public string? BinNumDescription { get; set; }
        public int? BitFlag { get; set; }
        public string? ChangeDate { get; set; }
        public string? ChangedBy { get; set; }
        public bool? CNDeclarationBill { get; set; }
        public int? CNDeclarationBillLine { get; set; }
        public string? CommodityCode { get; set; }
        public string? CommodityDescription { get; set; }
        public string? Company { get; set; }
        public bool? ComplianceMsg { get; set; }
        public bool? ConsolidatedPO { get; set; }
        public double? ContainerExtCost { get; set; }
        public int? ContainerID { get; set; }
        public double? ContainerLCAmt { get; set; }
        public string? ContractID { get; set; }
        public bool? ContractOrder { get; set; }
        public bool? ConvOverride { get; set; }
        public string? CostPerCode { get; set; }
        public double? CostPerFactor { get; set; }
        public string? CountryNumDescription { get; set; }
        public string? CurrencyCode { get; set; }
        public bool? Delivered { get; set; }
        public string? DeliveredComments { get; set; }
        public string? DimCode { get; set; }
        public string? DimCodeDimCodeDescription { get; set; }
        public double? DimConvFactor { get; set; }
        public bool? DisableInspection { get; set; }
        public string? DisplayUMField { get; set; }
        public double? DocInUnitCost { get; set; }
        public double? DocInVendorUnitCost { get; set; }
        public double? DocScrUnitCost { get; set; }
        public double? DocScrVendorUnitCost { get; set; }
        public double? DocUnitCost { get; set; }
        public double? DocVendorUnitCost { get; set; }
        public bool? DropShipment { get; set; }
        public string? DUM { get; set; }
        public DateTime? DueDate { get; set; }
        public bool? EnableBin { get; set; }
        public bool? EnableDim { get; set; }
        public bool? EnableInventoryAttributes { get; set; }
        public bool? EnableLot { get; set; }
        public bool? EnablePCID { get; set; }
        public bool? EnableSN { get; set; }
        public bool? EnableSupplierXRef { get; set; }
        public bool? EnableTransValue { get; set; }
        public bool? EnableUplift { get; set; }
        public bool? EnableWhse { get; set; }
        public bool? EpicorFSA { get; set; }
        public double? ExtCost { get; set; }
        public double? ExtNonRecoverableCost { get; set; }
        public double? ExtTransValue { get; set; }
        public double? FailedQty { get; set; }
        public string? GlbCompany { get; set; }
        public int? GlbPackLine { get; set; }
        public string? GlbPackSlip { get; set; }
        public string? GlbPurPoint { get; set; }
        public int? GlbVendorNum { get; set; }
        public double? GrossWeight { get; set; }
        public string? GrossWeightUOM { get; set; }
        public bool? HHReceiveToPCID { get; set; }
        public int? ICPackNum { get; set; }
        public int? ImportNum { get; set; }
        public int? ImportedFrom { get; set; }
        public string? ImportedFromDesc { get; set; }
        public double? InAppliedLCVariance { get; set; }
        public double? InAppliedRcptLCAmt { get; set; }
        public double? InLCSpecLineDutyAmt { get; set; }
        public double? InOurCost { get; set; }
        public double? InputOurQty { get; set; }
        public bool? InspectionFlag { get; set; }
        public bool? InspectionPending { get; set; }
        public bool? InspectionReq { get; set; }
        public string? InspectorID { get; set; }
        public string? InspectorIDName { get; set; }
        public string? InspectedBy { get; set; }
        public DateTime? InspectedDate { get; set; }
        public int? InspectedTime { get; set; }
        public double? IntQueID { get; set; }
        public string? InvoiceNum { get; set; }
        public string? InvoiceNumDescription { get; set; }
        public int? InvoiceLine { get; set; }
        public bool? IssuedComplete { get; set; }
        public string? IUM { get; set; }
        public string? JobIUM { get; set; }
        public string? JobNum { get; set; }
        public string? JobNumPartDescription { get; set; }
        public string? JobPartNum { get; set; }
        public double? JobRequiredQty { get; set; }
        public string? JobSeqType { get; set; }
        public int? JobSeq { get; set; }
        public string? LegalNumber { get; set; }
        public string? LegalNumberMessage { get; set; }
        public double? LCDutyAmt { get; set; }
        public double? LCMtlBurUnitCost { get; set; }
        public double? LCSpecLineDutyAmt { get; set; }
        public double? LCUpliftIndCost { get; set; }
        public string? LotNum { get; set; }
        public bool? ManualLC { get; set; }
        public string? MangCustID { get; set; }
        public int? MangCustNum { get; set; }
        public string? MangCustName { get; set; }
        public bool? MassReceipt { get; set; }
        public double? MtlBurRate { get; set; }
        public bool? NonConformnce { get; set; }
        public bool? NoTaxRecalc { get; set; }
        public int? NumLabels { get; set; }
        public string? OnTime { get; set; }
        public bool? OpenRelease { get; set; }
        public int? OrderLine { get; set; }
        public int? OrderNum { get; set; }
        public double? OrderQty { get; set; }
        public int? OrderRelNum { get; set; }
        public int? OrigCountryNum { get; set; }
        public double? OurMtlBurUnitCost { get; set; }
        public double? OurQty { get; set; }
        public double? OurRemQty { get; set; }
        public double? OurUnitCost { get; set; }
        public double? OurUnInvcReceiptQty { get; set; }
        public int? PackLine { get; set; }
        public string? PackSlip { get; set; }
        public string? PartDescription { get; set; }
        public string? PartNum { get; set; }
        public string? PartNumAttrClassID { get; set; }
        public string? PartNumIUM { get; set; }
        public string? PartNumPartDescription { get; set; }
        public string? PartNumPricePerCode { get; set; }
        public double? PartNumSellingFactor { get; set; }
        public string? PartNumSalesUM { get; set; }
        public bool? PartNumTrackDimension { get; set; }
        public bool? PartNumTrackInventoryAttributes { get; set; }
        public bool? PartNumTrackLots { get; set; }
        public bool? PartNumTrackSerialNum { get; set; }
        public double? PassedQty { get; set; }
        public string? PCID { get; set; }
        public bool? PCIDOutboundContainer { get; set; }
        public bool? PCIDStatusChanged { get; set; }
        public bool? PkgControlStatus { get; set; }
        public string? Plant { get; set; }
        public string? POComment { get; set; }
        public DateTime? PODueDate { get; set; }
        public double? POFactor { get; set; }
        public string? POFactorDirection { get; set; }
        public bool? POHold { get; set; }
        public string? POIUM { get; set; }
        public int? POLine { get; set; }
        public string? POLineLineDesc { get; set; }
        public string? POLinePartNum { get; set; }
        public string? POLineVenPartNum { get; set; }
        public int? PONum { get; set; }
        public string? PONumApprovalStatus { get; set; }
        public bool? PONumApprove { get; set; }
        public bool? PONumConfirmed { get; set; }
        public string? PONumShipName { get; set; }
        public string? PONumShipToConName { get; set; }
        public string? POPUM { get; set; }
        public double? POTransValue { get; set; }
        public string? POType { get; set; }
        public int? PORelNum { get; set; }

        public string? PUM { get; set; }

        public bool? ProjProcessed { get; set; }
        public string? ProjectCode_c { get; set; }
        public string? PurPoint { get; set; }
        public string? PurPointAddress1 { get; set; }
        public string? PurPointAddress2 { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointCountry { get; set; }
        public string? PurPointName { get; set; }
        public int? PurPointPrimPCon { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointZip { get; set; }
        public string? PurchCode { get; set; }
        public string? PurchCodePurchDesc { get; set; }
        public string? QtyOption { get; set; }
        public double? RcvdSMIQty { get; set; }
        public DateTime? ReceiptDate { get; set; }
        public string? ReceiptType { get; set; }
        public bool? Received { get; set; }
        public bool? ReceivedComplete { get; set; }
        public double? ReceivedQty { get; set; }
        public string? ReceivedTo { get; set; }
        public string? RefCode { get; set; }
        public string? RefType { get; set; }
        public string? ReqCategory_c { get; set; }
        public string? RevisionNum { get; set; }
        public string? RowMod { get; set; }
        public double? Rpt1InUnitCost { get; set; }
        public double? Rpt1ScrUnitCost { get; set; }
        public double? Rpt1ScrVendorUnitCost { get; set; }
        public double? Rpt1UnitCost { get; set; }
        public double? Rpt1VendorUnitCost { get; set; }
        public double? Rpt2InUnitCost { get; set; }
        public double? Rpt2ScrUnitCost { get; set; }
        public double? Rpt2ScrVendorUnitCost { get; set; }
        public double? Rpt2UnitCost { get; set; }
        public double? Rpt2VendorUnitCost { get; set; }
        public double? Rpt3InUnitCost { get; set; }
        public double? Rpt3ScrUnitCost { get; set; }
        public double? Rpt3ScrVendorUnitCost { get; set; }
        public double? Rpt3UnitCost { get; set; }
        public double? Rpt3VendorUnitCost { get; set; }
        public double? ScrOurUnitCost { get; set; }
        public double? ScrVendorUnitCost { get; set; }
        public int? SearchPONum { get; set; }
        public bool? Selected { get; set; }
        public int? SerialNoAttributeSetID { get; set; }
        public string? ShipRcv { get; set; }
        public bool? SMIComplete { get; set; }
        public int? SMITransNum { get; set; }
        public bool? SNStusChanged { get; set; }
        public double? SupplierUnInvcReceiptQty { get; set; }
        public int? SysRevID { get; set; }
        public Guid? SysRowID { get; set; }
        public int? TagMtlSeq { get; set; }
        public int? TagOprSeq { get; set; }
        public string? TaxCatID { get; set; }
        public string? TaxCatIDDescription { get; set; }
        public string? TaxExempt { get; set; }
        public string? TaxRegionCode { get; set; }
        public bool? Taxable { get; set; }
        public double? ThisTranQty { get; set; }
        public string? ThisTranUOM { get; set; }
        public double? TotCostVariance { get; set; }
        public double? TotDedTaxAmt { get; set; }
        public double? TotDutiesAmt { get; set; }
        public double? TotLineAmt { get; set; }
        public double? TotSATaxAmt { get; set; }
        public double? TotTaxAmt { get; set; }
        public double? TotWHTaxAmt { get; set; }
        public double? TotalAmt { get; set; }
        public string? TranReference { get; set; }
        public string? TranType { get; set; }
        public double? UpliftPercent { get; set; }
        public bool? UsePurchaseCode { get; set; }
        public string? VenPartNum { get; set; }
        public double? VenRemQty { get; set; }
        public string? VendorCurrSymbol { get; set; }
        public int? VendorNum { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumState { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumZIP { get; set; }
        public double? VendorQty { get; set; }
        public double? VendorUnitCost { get; set; }
        public double? Volume { get; set; }
        public string? VolumeUOM { get; set; }
        public string? WareHouseCode { get; set; }
        public string? WareHouseCodeDescription { get; set; }
        public double? Weight { get; set; }
        public string? WeightUOM { get; set; }
        public double? PORelArrivedQty { get;  set; }
    }

    public class RcvAttachment
    {
        public string Data { get; set; }
        public string DocTypeID { get; set; }
        public string FileName { get; set; }
        public string ParentTable { get; set; }
        public string DrawDesc { get; set; }

        public string PackSlip {  get; set; }
        public string RowMod { get; set; }
        public int VendorNum { get; set; }
        public string nik { get; set; }
        public string password { get; set; }
    }

    public class RcvHeadAttch
    {
        public string Company { get; set; }
        public string DocTypeID { get; set; }
        public string DrawDesc { get; set; }
        public int DrawingSeq { get; set; }
        public string FileName { get; set; }
        public string ForeignSysRowID { get; set; }
        public string PDMDocID { get; set; }
        public string PackSlip { get; set; }
        public string PurPoint { get; set; }
        public string RowMod { get; set; }
        public int SysRevID { get; set; }
        public string SysRowID { get; set; }
        public int VendorNum { get; set; }
        public int XFileRefNum { get; set; }
    }
}
